### ISSUE TITLE
Please update dask-cuda on pypi

### ISSUE THREAD

**Issue by sh1ng** [rapidsai/dask-cuda#166]
Hi,

After reading you explanation(https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472) regarding stop support of PyPI I want to add some thoughts and spotlight a few solutions that were not to mention in the post.

- PyPI is a main source of packages that why tensorflow originally publish it as `manylinux` 
- Not every project can(or want) to use conda instead of native python
- `manylinux2010` https://www.python.org/dev/peps/pep-0571/ allows to use CentOS 6 which is supported by CUDA
- You can use `devtoolset-*` to install appropriate version of compiler and without  need to ship `libstdc++.so` etc.

**Comment by mrocklin** [comment]
Closing in favor of https://github.com/rapidsai/dask-cuda/issues/130

If you want to have a conversation about RAPIDS pip support generally you should probably target a repository like cudf rather than dask-cuda, which is a much easier case.  If you just want dask-cuda on PyPI then this is much more technically feasible, and is only a policy decision.  The issue above has more people on it, so I would encourage you to chime in there.
