### ISSUE TITLE
CUDA_VISIBILE_DEVICES and nccl on multi-GPU machines

### ISSUE THREAD

**Issue by hhuuggoo** [rapidsai/dask-cuda#516]
with PyTorch 1.7 on a machine with 4 V100s, If I try to call `torch.distributed.init_process_group` with `nccl` I get the following error

```
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729066392/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```

I've tracked this down to the env-var rotation of `CUDA_VISIBLE_DEVICES`.  If I disable this line:

https://github.com/rapidsai/dask-cuda/blob/branch-0.18/dask_cuda/cuda_worker.py#L212

initializing the torch process group is fine.

I *think* (not not 100% sure on my recollection) that this used to work on PyTorch 1.6.  But I'm posting this issue here because I wanted to ask if rotating `CUDA_VISIBLE_DEVICES` is a good thing to do with nccl, or if it should be disabled?

**Comment by jakirkham** [comment]
So Dask-CUDA makes the design choice to have 1 GPU visible to 1 Dask Worker. It does this by setting which device is visible to which Worker, which it has done basically since this code existed.

My suspicion is PyTorch has made some kind of change on how it works with NCCL. Maybe there is a way to configure 1.7 to get the 1.6 behavior?

**Comment by quasiben** [comment]
Can you post a minimal reproducer with dummy data ?

**Comment by pentschev** [comment]
This has gone stale. I'm closing, but feel free to reopen if this is still relevant.
