### ISSUE TITLE
dask-cuda-worker isn't able to connect to dask-scheduler using websocket protocol...

### ISSUE THREAD

**Issue by sriramch** [rapidsai/dask-cuda#667]
```
(rapids) root@2103694:/rapids/notebooks# dask-scheduler --version
dask-scheduler, version 2021.6.1

(rapids) root@2103694:/rapids/notebooks# dask-worker --version
dask-worker, version 2021.6.1

(rapids) root@2103694:/rapids/notebooks# pip list | grep -i dask
dask                          2021.6.1
dask-cuda                     0+untagged.1.gf3220a4
dask-cudf                     0+untagged.1.g788bddd
dask-glm                      0.2.0
dask-labextension             5.0.2
dask-ml                       1.9.0
```

dask scheduler is running on standard ports using `ws` procotol. traffic to it is proxied.

```
root          1      0  0 19:13 ?        00:00:00 /bin/sh -c /opt/docker/bin/entrypoint --unquote-exec dask-scheduler --dashboard-address :8787 --port 8786 --protocol ws
root          6      1  3 19:13 ?        00:00:24 /opt/conda/envs/rapids/bin/python /opt/conda/envs/rapids/bin/dask-scheduler --dashboard-address :8787 --port 8786 --protocol ws
```

i'm trying to connect to this scheduler from another node using both `dask-cuda-worker` and `dask-worker`.

`dask-worker` is able to connect, but *not* `dask-cuda-worker`

```
(rapids) root@2103694:/rapids/notebooks# dask-worker wss://proxy_endpoint:443 --protocol ws
distributed.nanny - INFO -         Start Nanny at: 'ws://100.103.223.134:40227'
distributed.worker - INFO -       Start worker at: ws://100.103.223.134:44835
distributed.worker - INFO -          Listening to: ws://100.103.223.134:44835
distributed.worker - INFO -          dashboard at:      100.103.223.134:42105
distributed.worker - INFO - Waiting to connect to: wss://proxy_endpoint:443
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                  50.00 GiB
distributed.worker - INFO -       Local Directory: /rapids/notebooks/dask-worker-space/worker-764djlbo
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to: wss://proxy_endpoint:443
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection

```

`dask-cuda-worker`

```
(rapids) root@2103694:/rapids/notebooks# dask-cuda-worker wss://proxy_endpoint:443 --protocol ws
Usage: dask-cuda-worker [OPTIONS] [SCHEDULER] [PRELOAD_ARGV]...

Error: no such option: --protocol
```

tried without the `--protocol`

```
(rapids) root@2103694:/rapids/notebooks# dask-cuda-worker wss://proxy_endpoint:443
...

TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
```

@jacobtomlinson - fyi.

**Comment by pentschev** [comment]
The protocol is inferred by the scheduler address (the bit before `://`) and thus unnecessary to be specified with `--protocol`, that's why Dask-CUDA doesn't implement it. You're trying to connect to `wss://` (with double `s`) where you should be connecting to `ws://`, thus the protocol is being inferred incorrectly and causing the issue you're seeing.

**Comment by sriramch** [comment]
> and thus unnecessary to be specified with --protocol

yes, tried it without the `--protocol` option, but then got the tls error as pasted earlier.

> You're trying to connect to wss:// (with double s) where you should be connecting to ws://

the proxy endpoint is a tls endpoint and thus can't connect using `ws`. furthermore, `dask-worker` is able to correctly connect to the scheduler via the proxy endpoint with `wss`. 

the scheduler is running behind an ssl proxy. the proxy terminates the tls and communicates with scheduler in plain text. that was the reason why `wss` was used to connect to the tls proxy endpoint.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @sriramch.

Running `dask-worker wss://proxy_endpoint:443 --protocol ws` actually connects with plain `ws` and seems to be working for you. 

Dask uses mutual TLS for authentication so running `dask-cuda-worker wss://proxy_endpoint:443` is failing because it expects you to provide client-side certs. We could definitely make this error better.

Despite the proxy endpoint adding a TLS layer I am curious what would happen if you did `dask-cuda-worker ws://proxy_endpoint:443`. My guess is that it would try to make a regular connection and that connection would get upgraded by the proxy. The fact that you did it successfully with `dask-worker` makes me think it would work.

**Comment by jacobtomlinson** [comment]
I've raised dask/distributed#5038 to cover the opaque error message.

**Comment by sriramch** [comment]
> Running dask-worker wss://proxy_endpoint:443 --protocol ws actually connects with plain ws (despite the prefix) and seems to be working for you

i doubt it @jacobtomlinson. the proxy endpoint terminates the tls, and thus the client has to do tls for the connection to be established. i have confirmed this via `tcpdump` - the connection is indeed encrypted.

> Dask uses mutual TLS for authentication so running dask-cuda-worker wss://proxy_endpoint:443 is failing because it expects you to provide client-side certs. 

at least the ingress (proxy) isn't enforcing `mTLS`. this is also evident by the fact that the `dask-worker` is able to connect to this proxy endpoint without doing `mTLS`. 

that said, i was able to bring up `dask-cuda-worker` with `--tls-ca-file /opt/conda/envs/rapids/ssl/cert.pem --tls-cert myca.pem --tls-key mykey.pem`, where `my{ca|key}` is a self signed certificate and its private key. however, i'm unable to use a `dask.distributed` client to submit tasks to it. i see this on the client:

```
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'sum-403a3bb7c99facf94d988136f4f09e6e': ('wss://100.103.248.90:38961',)}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'sum-403a3bb7c99facf94d988136f4f09e6e': ('wss://100.103.248.90:38961',)}
...
```
and this when i terminate the `dask-cuda-worker`:

```
distributed.comm.ws - INFO - Closing dangling websocket in <WSS  local=wss://proxy_endpoint:443 remote=wss://proxy_endpoint:443>
distributed.comm.ws - INFO - Closing dangling websocket in <WSS  local=wss://proxy_endpoint:443 remote=wss://proxy_endpoint:443>
...
```

note however that the `dask.distributed` client is able to successfully connect and submit tasks when `dask-worker` is started *without* any of the tls options using the `wss` protocol. it can *also* work with all of those tls options. the `--protocol ws` seems to be the key here.

i suspect that if `dask-cuda-worker` supports a `--protocol` option similar to `dask-worker`, it'll work as well (and there will be symmetry in terms of the the options supported by the 2 applications). 

> I am curious what would happen if you did dask-cuda-worker ws://proxy_endpoint:443

it wouldn't work. it'll repeatedly try connecting to the secure port via an insecure protocol and fail.

```
distributed.worker - INFO - Waiting to connect to: ws://proxy_endpoint:443
distributed.worker - INFO - Waiting to connect to: ws://proxy_endpoint:443
...

BK...b..HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: text/html
Content-Length: 264
Connection: close

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jacobtomlinson** [comment]
Thanks for the info @sriramch. That does make sense.

It seems like you are starting the Dask cluster with `ws` and then running it behind an nginx proxy which is adding a layer of HTTPS (`wss`). 

So Dask needs to connect to the nginx instance wth the correct request type by specifying `wss://host:port` but then the worker needs to speak to the scheduler directly via unsecured `ws`. So you're right that we do need a way to specify the comm protocol separately from the URL.

I'll get a PR raised to address this.

Out of interest why is the worker communication happening via the proxy? Is it not within the cluster and can connect via a private network?

**Comment by jacobtomlinson** [comment]
@pentschev in this instance it seems we need to be able to configure the address and protocol independently because an SSL/TLS proxy is involved.

**Comment by sriramch** [comment]
>Out of interest why is the worker communication happening via the proxy? Is it not within the cluster and can connect via a private network?

@jacobtomlinson this was mainly experimental. remember the conversation we have been having about spinning workers on different `k8s` clusters and have them connect to a scheduler running on a another `k8s` cluster (for scaling)? it is in that context, i have playing around to see how it may work in such cases. i was hoping that i would be able to connect to the scheduler indirectly via a proxy endpoint which will hide the scheduler. as i mentioned before, i was only evaluating the technical feasibility at this point, and the performance implications you raise is well taken.

it is required of course for the clients to connect to the scheduler via the proxy endpoint and submit jobs.

**Comment by pentschev** [comment]
> @pentschev in this instance it seems we need to be able to configure the address and protocol independently because an SSL/TLS proxy is involved.

Why does the user have to specify the protocol? It feels to me like Distributed should instead be able to parse `wss://` correctly as the TLS-enabled protocol, rather than having the user specify `--protocol wss`, IOW, specifying `wss://` is otherwise redundant (not to say useless).

**Comment by jacobtomlinson** [comment]
@pentschev distributed has the ability to speak `wss` with `mTLS` so that you can secure your scheduler. Distributed can also run in regular `ws` mode with no auth. However that's not what we are discussing here.

If you start a Dask scheduler in `ws` mode and then place a reverse proxy in front an additional layer of encryption can be added by the proxy. This is just regular TLS, not the mTLS that Dask uses. This is super common when exposing web services to the internet and is used by some HPCs to expose internal services to users.

In this scenario the `ws` connection will be upgraded by the proxy to `wss`, and so the worker needs to connect on `wss://some.proxy.com:443` but the onward connection to the Dask scheduler at the other end is still plain `ws`. So we need to set the protocol to `ws` explicitly even though the address needs to be `wss://`.

Distributed already supports this today because you can do `dask-worker wss://some.proxy.com:443 --protocol ws`. The goal here is feature parity in `dask-cuda`.

**Comment by pentschev** [comment]
Can you explain then what's the role of `wss://` specifically? To my understanding, it's going to be dropped and treated by whatever is that `--protocol` specifies in https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/nanny.py#L148-L151 . In practice, this means that whatever you specify with `protocol://` is just ignored, which would make `anything://some.proxy.com:443 --protocol ws` just as acceptable as `wss://some.proxy.com:443 --protocol ws`. What I'm saying is that, IMO, Distributed should instead check `wss://some.proxy.com:443` and infer `--protocol ws` from that.

We don't intend necessarily to offer full-feature parity with Distributed as we would like to defer as much as possible to Distributed itself. As per what I wrote just above, it still seems to me that this is something Distributed could handle in a more user-friendly manner which would in turn allow Dask-CUDA not to handle `--protocol` directly.

**Comment by jacobtomlinson** [comment]
I followed the same train of thought, however it turns out it is not ignored.

You're right that the protocol [can be inferred by the address](https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/nanny.py#L148-L151). But the [address is not updated if the protocol is set](https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/nanny.py#L144).

My understanding is that the address is used to establish the connection, and the protocol is used to fire content down the pipe.

> What I'm saying is that, IMO, Distributed should instead check wss://some.proxy.com:443 and infer --protocol ws from that.

Both `ws` and `wss` are valid protocols for a `wss://some.proxy.com:443` address.

Distributed has no way of knowing whether the scheduler on the other side of the proxy is `ws` or `wss`. It will assume `wss` because of the address. In this scenario we need to a way to be explicit that the protocol is still `ws`.

> We don't intend necessarily to offer full-feature parity with Distributed as we would like to defer as much as possible to Distributed itself.

I totally agree, and distributed handles this use case. But in this case I do not think we can defer any kind of inference. The user needs a way to explicitly set this configuration via the CLI API here.

**Comment by jacobtomlinson** [comment]
I think part of the problem here is that when we set `wss` or `tls` [we assume we care about security and authentication](https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/comm/ws.py#L361) via mTLS. But in this case we do not.

**Comment by pentschev** [comment]
> My understanding is that the address is used to establish the connection upstream, and the protocol is used to start the listener on the worker.

Aha! Interesting, I didn't know this was an acceptable pattern. Honestly I feel this is a dangerous pattern for some cases, I just tested starting `dask-scheduler --protocol ucx` with `dask-worker ucx://SCHEDULER_IP:8786 --protocol tcp` and the worker indeed connects to the scheduler with UCX but listens using the TCP communication protocol, this is certainly going to create lots of problems and is very easy to ignore when debugging.

I agree that in the particular case being discussed here then `--protocol` is required, but I wish there was a better way, or at least some sort of warning to make sure users understand what they're really doing.

**Comment by pentschev** [comment]
> If you start a Dask scheduler in `ws` mode and then place a reverse proxy in front an additional layer of encryption can be added by the proxy. This is just regular TLS, not the mTLS that Dask uses. This is super common when exposing web services to the internet and is used by some HPCs to expose internal services to users.

Also orthogonal to the discussion here, but aren't users gonna be limited to how they can use the cluster? For example, I imagine `client.run` will not work in this case, as the `client` needs to be able to connect to workers directly.

**Comment by jacobtomlinson** [comment]
>  I didn't know this was an acceptable pattern.

The `ws` protocol was introduced intentionally to be used for the `client <=> scheduler` comms while the `scheduler <=> worker` and `worker <=> worker` can be something else. This is to allow HTTP proxies to proxy the scheduler comm to the client.

> this is certainly going to create lots of problems and is very easy to ignore when debugging.

Yeah this hasn't come up much yet but I think it might in the future.

> For example, I imagine client.run will not work in this case, as the client needs to be able to connect to workers directly.

It looks like `run` goes via the scheduler.

https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/client.py#L2463

We have many deployment options where the client cannot communicate directly with the workers. Dask Cloudprovider, Dask Kubernetes, Dask yarn and Dask Gateway all operate this way. I generally assume that `client <=> worker` comms is never possible.

**Comment by pentschev** [comment]
> It looks like `run` goes via the scheduler.
> 
> https://github.com/dask/distributed/blob/d7b64167dd3c643381425139f6f5ad4fb5363928/distributed/client.py#L2463

Yes, you're right. I think I always thought the client would directly communicate with the worker because it's being run on a separate communication channel, i.e., there will be new endpoints being created on each of the workers, but they come from the scheduler and not from the client as I believed to be the case. Thanks for pointing that out to me.
