### ISSUE TITLE
Restarting a cluster after teardown requires a larger time gap with ucx 1.11

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/dask-cuda#676]
Not sure if ucx-py is a better place to open this issue. 

While creating clusters from the commandline (with UCX), I've noticed a lot more errors with UCX1.11 while starting up the scheduler if there isn't enough time gap from when the previous cluster was shutdown. 
```python
File "ucp/_libs/utils.pyx", line 108, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Device is busy
```

Not sure if this difference in behavior b/w ucx1.9 and 1.11 is expected (or intended), but in practice I need to typically sleep 60 seconds before attempting to startup a new cluster.

**Comment by pentschev** [comment]
Yes, this is known and should only happen _without IB_, can you confirm this is your case too? The workaround for that is to set `UCX_TCP_CM_REUSEADDR=y`. Unfortunately, this is due to the closing mechanism in UCX and there's nothing we can do on the UCX-Py or Dask side apart from defining that environment variable.

**Comment by ayushdg** [comment]
> should only happen without IB, can you confirm this is your case too?
Yup this is without IB. I'll try using the environment variable and see if that helps with the shutdown mechanism. Thanks for the suggestion.

**Comment by ayushdg** [comment]
Just wanted to update that setting `UCX_TCP_CM_REUSEADDR=y` fixed the issues.
