### ISSUE TITLE
Warnings about existing CUDA contexts on dask-cuda cluster startup

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#721]
On starting up a dask-cuda cluster on a DGX2, I get this warning for every worker:
```
/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_cuda/initialize.py:22: UserWarning: A CUDA context for device 14 already exists on process ID 3287969. This is often the result of a CUDA-enabled library calling a CUDA runtime function before Dask-CUDA can spawn worker processes. Please make sure any such function calls don't happen at import time or in the global scope of a program.
  warnings.warn(
```

Checking nvidia-smi, I only see one process per GPU, so nothing looks out of the ordinary despite the warning suggesting I may have multiple workers on a single GPU.

**Comment by pentschev** [comment]
This is due to https://github.com/rapidsai/dask-cuda/pull/719 . The warning happens with UCX only because we do create the [CUDA context in Distributed](https://github.com/dask/distributed/blob/0774365a305a22f05ff916318bdba57add3f2eb7/distributed/comm/ucx.py#L52-L63) (Distributed comms initializes before initializer plugins that are used by Dask-CUDA). So I’ll need to rewire things a bit in Distributed.

**Comment by pentschev** [comment]
Opened https://github.com/dask/distributed/pull/5308 and https://github.com/rapidsai/dask-cuda/pull/722, they should be enough to address the issue here.

**Comment by pentschev** [comment]
This is in, thanks for reporting @randerzander and please let me know if you experience any problems still.
