### ISSUE TITLE
Document GPU best practices

### ISSUE THREAD

**Issue by jrbourbeau** [rapidsai/dask-cuda#750]
Some colleagues and I have started using distributed Dask clusters with GPU-enabled workers. During a quick chat with @quasiben, a few best practices came up (@quasiben feel free to correct me if I misunderstood your suggestions):

- Make sure to use `dask_cuda.CUDAWorker` for your cluster workers
- Set `rmm_pool_size` to be 80-90% of machine’s memory 
- Set `device_memory_limit` to be 60% of machine’s memory
- ...

I was wondering if there are other best practices the `dask-cuda` developers have for someone getting started with using GPUs in Dask clusters? Additionally, is there any interest in having a "Best Practices" page, similar to https://docs.dask.org/en/stable/best-practices.html, in the `dask-cuda` docs?

**Comment by ayushdg** [comment]
Totally agree that a best practices page would be valuable. Based on my experience with gpu-bdb and other benchmarks here's what I've observed:
- device_memory_limit: ~ 55-60% if `DASK_JIT_UNSPILL=True`,  ~ 80% if false (since spilling is much faster and it enables more memory intensive operations at a much lower perf cost)
- rmm_pool_size: leave around 2GB of total gpu memory free. This usually amounts to ~90-98% of GPU memory on most cards. With the caveat that the workflow needs to account for any large data that might be computed and brought back to the client process with `compute`.
- Set `DASK_RMM__POOL_SIZE` ~0.5GB when working with the `ucx` protocol.

Potentially also worth either adding a separate section for UCX specific configuration recommendations or linking to [this page](https://docs.rapids.ai/api/dask-cuda/nightly/ucx.html#configuration) in the dask-cuda docs from the best practices page as well.
