### ISSUE TITLE
cp.RawKernel and LocalCUDACluster

### ISSUE THREAD

**Issue by garanews** [rapidsai/dask-cuda#85]
I have code running with dask LocalCUDACluster and cupy.
I would improve speed using rawkernel from cupy.
I have code with cupy and rawkernel working but don't know why running it with dask LocalCUDACluster is giving me wrong results (and or errors).
Basically I would use dask LocalCUDACluster  because have multiple GPU and because the data in input don't fit in RAM.
Some basic question: 
with cp.RawKernel must the input matrixt be square?  
how manage the return of cp.RawKernel function in map_partitions ? I think the value will be overwritten every chunk processed.
There is someone already tried something like that?

**Comment by pentschev** [comment]
> with cp.RawKernel must the input matrixt be square?

I have no experience with `cupy.RawKernel` specifically. Documentation doesn't have any mention to square matrices, so I would say they don't need to be square, but I'd ask in https://github.com/cupy/cupy or on StackOverflow to be certain.

> how manage the return of cp.RawKernel function in map_partitions ? I think the value will be overwritten every chunk processed.

Note that `map_partitions` is used for Dask bag/dataframe, not for Dask array. Since you're working with CuPy (which you map to a Dask array), you're probably looking for [`map_blocks`](https://docs.dask.org/en/latest/array-api.html#dask.array.core.map_blocks) or [`map_overlap`](https://docs.dask.org/en/latest/array-overlap.html).

> There is someone already tried something like that?

I am not aware of anyone who tried using `cupy.RawKernel` with dask-cuda yet.

**Comment by garanews** [comment]
Thanks for the answer. About cupy square question I tried stackoverflow.
About your suggestion map_blocks I did some test without success.
I posted last version of code here: https://gist.github.com/garanews/ca7751175f47b669bcbbf8349c1fac38
You can see the working code without dask and some attempt to use dask with map_blocks.

Any help will be much appreciated. :)

**Comment by pentschev** [comment]
To be honest, I don't quite understand what you're trying to do. Regardless, I wrote a [simple example](https://gist.github.com/pentschev/d66014ec27b331a74a15f7c48dca0121). I hope it helps shed some light upon your work.

**Comment by pentschev** [comment]
By the way, I didn't write it to be robust, so be aware that proper checks may be required if arbitrary sizes are to be passed to the kernel.

**Comment by garanews** [comment]
Thanks for the code, I'll have a look.
To describe better what I am trying to do I uploaded a picture https://user-images.githubusercontent.com/16938405/60419737-50afe980-9be6-11e9-96c1-0339a78bd015.png

**Comment by garanews** [comment]
Thanks to your help I updated the code: https://gist.github.com/garanews/ca7751175f47b669bcbbf8349c1fac38
Both my questions have been addressed, we can consider This issue closed.
