### ISSUE TITLE
nprocs deprecated in dask-worker

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#851]
In https://github.com/dask/distributed/pull/5641 Dask has begun deprecating `--nprocs` .  Dask-cuda should probably do the same

**Comment by pentschev** [comment]
Besides a couple of `dask-cuda-worker` argument descriptions [here](https://github.com/rapidsai/dask-cuda/blob/9a928641f3379f2097bcac390d64727f82812dfa/dask_cuda/cli/dask_cuda_worker.py#L46) and [here](https://github.com/rapidsai/dask-cuda/blob/9a928641f3379f2097bcac390d64727f82812dfa/dask_cuda/cli/dask_cuda_worker.py#L131), there are no other uses for `--nprocs`. In fact, I think they are even wrong since we don't expose `--nprocs` as `click` arguments:

```
$ dask-cuda-worker 127.0.0.1 --nprocs 3
Usage: dask-cuda-worker [OPTIONS] [SCHEDULER] [PRELOAD_ARGV]...
Try 'dask-cuda-worker --help' for help.

Error: No such option: --nprocs
```

 I'll submit a PR to remove that.

**Comment by pentschev** [comment]
Submitted https://github.com/rapidsai/dask-cuda/pull/852 to remove such descriptions.
