### ISSUE TITLE
Using `await wait(client.compute(y))` is somehow faster than `await client.compute(y)`

### ISSUE THREAD

**Issue by YJHMITWEB** [rapidsai/dask-cuda#987]
Hi, I'm running Dask experiments across multiple server nodes. I found a weird behavior that using `await wait(client.compute(y))` is much faster than `await client.compute(y)`.

**Hardware**
```
Host memory: 128GB
Device: v100 with 32GB memory
Protocol: TCP over InfiniBand
```
**Conda environment**
```
dask                      2022.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2022.7.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 22.10.0a0+17.ga34baea           dev_0    <develop>
dask-cudf                 22.08.00        cuda_11_py38_gb71873c701_0    rapidsai
distributed               2022.7.1           pyhd8ed1ab_0    conda-forge
rmm                       22.08.00        cuda11_py38_gd212232c_0    rapidsai
cudatoolkit               11.1.1              ha002fc5_10    conda-forge
numba                     0.55.2           py38hdc3674a_0    conda-forge
cupy                      10.6.0           py38ha04ee3d_0    conda-forge
```

## What I do ##
```
Node#1 with one V100-32G, `dask-scheduler --interface ib0 --protocol ucx`, (ip: ucx://10.3.1.17:8888)
Node#2 with two K80-11G, `dask-worker ucx://10.3.1.17:8888  --interface ib0 --nworkers 2`
Node#3 with two K80-11G, `python test.py ucx://10.3.1.17:8888`
```

`test.py`:
```
import sys
import asyncio
import time
import dask.array as da
import dask.array.fft as daf
RUNS               =  5
async def f_fft(addr):
    async with Client(address=addr, asynchronous=True) as client:
        print(client)

        for i in range(RUNS):
            start = time.time()
            rs = da.random.RandomState(RandomState=cupy.random.RandomState)
            a = rs.random(size=(16*2**10, 16*2**9), chunks=(16*2**6, 16*2**9))
            y = daf.fft(a)
            await client.compute(y)
            duration = time.time() - start
            print("Time for iteration", i, ":", duration)
            sys.stdout.flush()

if __name__ == '__main__':
    addr = sys.argv[1]
    asyncio.get_event_loop().run_until_complete(f_fft(addr))
```
In this line `await client.compute(y)`, if I don't use `wait()` to wrap it, then the average time of computation is:
```
Time for iteration 0 : 3.664011240005493
Time for iteration 1 : 3.2987313270568848
Time for iteration 2 : 3.1850790977478027
Time for iteration 3 : 3.1647801399230957
Time for iteration 4 : 3.1625425815582275
```
however, using `await wait(client.compute(y))`, the average time of computation is:
```
Time for iteration 0 : 1.0176162719726562
Time for iteration 1 : 0.8819968700408936
Time for iteration 2 : 0.8831126689910889
Time for iteration 3 : 0.8810024261474609
Time for iteration 4 : 0.8944222927093506
```

I'm curious about this behavior, cause in other computation tasks instead of FFT here, using `wait()` also shows a difference but not that big.
For example, in a transpose_sum task:
```
import sys
import asyncio
import time
import dask.array as da
import dask.array.fft as daf
RUNS               =  5
async def f_transpose_sum(addr):
    async with Client(address=addr, asynchronous=True) as client:
        print(client)

        for i in range(RUNS):
            start = time.time()
            rs = da.random.RandomState(RandomState=cupy.random.RandomState)
            a = rs.normal(100, 1, size=(2**14, 2**14), chunks='auto')
            y = (a + a.T).sum()
            await client.compute(y)
            duration = time.time() - start
            print("Time for iteration", i, ":", duration)
            sys.stdout.flush()

if __name__ == '__main__':
    addr = sys.argv[1]
    asyncio.get_event_loop().run_until_complete(f_transpose_sum(addr))
```
In this line `await client.compute(y)`, if I don't use `wait()` to wrap it, then the average time of computation is:
```
Time for iteration 0 : 1.5944044589996338
Time for iteration 1 : 0.8998472690582275
Time for iteration 2 : 0.9019994735717773
Time for iteration 3 : 1.003342866897583
Time for iteration 4 : 0.9574573040008545
```
however, using `await wait(client.compute(y))`, the average time of computation is:
```
Time for iteration 0 : 1.655719518661499
Time for iteration 1 : 0.9316599369049072
Time for iteration 2 : 0.9104499816894531
Time for iteration 3 : 0.8664019107818604
Time for iteration 4 : 0.8596160411834717
```
I'm wondering why this is happening.

**Comment by YJHMITWEB** [comment]
In my following tests I found the gap between using `wait()` and not is highly related to the size of the data that I manipulated, larger the size, bigger the gap.

**Comment by wence-** [comment]
This is slightly subtle. When you call `client.compute(y)` you get back a [`distributed.Future`](https://distributed.dask.org/en/stable/api.html#future) representing the result of a computation. [`client.compute`](https://distributed.dask.org/en/stable/api.html#distributed.Client.compute) just queues up a computation on the cluster (it doesn't pull the data back to the client). If you now call `wait` on this future you're adding a synchronisation point waiting for the _workers_ to complete their computation which is itself a future of some kind.

So when you call `x = await wait(client.compute(y))` then your code is saying "please wait until you've completed computing `y` on the cluster".

Conversely, `x = await client.compute(y)` is shorthand for saying `x = await client.compute(y).result()`; that is: "unwrap the future and wait for it to complete". This latter _does_ provoke transfer of the distributed dask array back to the cluster. We can see this by inspecting the types of `x` in the two cases:

- `x = await wait(client.compute(y)); type(x) => <class 'concurrent.futures._base.DoneAndNotDoneFutures'>`
- `x = await client.compute(y); type(x) => <class 'cupy.ndarray'>`

So the reason the gap is related to the size of the data (and increases when you make the data size bigger) is because in the "slow" case you're transferring data back to the client, whereas in the former case you're just waiting for the FFT to be carried out on the cluster.

For some of the conceptual aspects of how dask and distributed work, it may also be worthwhile (if you haven't already!) reading through some of the dask documentation (there's a nice list of [tutorials](https://docs.dask.org/en/stable/presentations.html) on the dask website, as well as [best practices](https://docs.dask.org/en/stable/best-practices.html); the distributed documentation is perhaps a bit more developer-focused, but the [quickstart](https://distributed.dask.org/en/stable/quickstart.html) is a good place to look too).

Thanks!

**Comment by YJHMITWEB** [comment]
Yes, I see. Thanks a lot for the reply!
